# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np
arr = np.random.randint(0, 20, (4, 7))
arr

array([[ 9, 16,  0,  9, 11,  1, 14],
       [10, 10,  5, 11,  5, 16,  4],
       [ 1,  2,  1,  2, 10,  9, 11],
       [18, 12, 14,  3, 15, 13,  0]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
a = np.array([2,3,4])
print(type(a))
b = [2,3,4]
print(np.array(b))
print(np.arange(5))


<class 'numpy.ndarray'>
[2 3 4]
[0 1 2 3 4]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1.1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np
first_five_rows = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1, max_rows=5)
first_five_rows

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
rows = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int64, skiprows=1)
column_1, column_2 = rows[:, 1], rows[:, 2]
print(column_1)
print(f'Average values: {column_1.mean()}, {column_2.mean()}')
print(f'Minimum: {column_1.min()}, {column_2.min()}')
print(f'Maximum: {column_1.max()}, {column_2.max()}')
print(f'Median: {np.median(column_1)}, {np.median(column_2)}')

[ 60  25  10 ...  65   5 140]
Average values: 21601.00169, 9.05528
Minimum: 0, 1
Maximum: 2147483647, 39
Median: 40.0, 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [ ]:
quant = np.quantile(column_1, 0.75)
print(quant)
print([rows[:, 1] > quant])
rows[:, 1][rows[:, 1] > quant] = quant #все значения в столбце времени, что больше квантиля, заменил на значение квантиля
print(rows)

65.0
[array([False, False, False, ..., False, False, False])]
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
print(len(rows[:, 1][rows[:, 1] == 0]))
print([rows[:, 1] == 0])
rows[:, 1][rows[:, 1] == 0] = 1
print(rows)

479
<class 'list'>
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
column_0 = rows[:, 0]
print(f'Число уникальных рецептов в датасете: {len(np.unique(column_0))}')

Число уникальных рецептов в датасете: 100000


In [ ]:
rows

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]], dtype=int64)

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
unique,counts = np.unique(rows[:, 1:3], return_counts=True)
print(counts)
print(f'Значения кол-ва ингредиентов: {unique}')
print(f'Число значений кол-ва ингредиентов: {len(unique)}')

[  729  1738  3358  5783 11997  9723 11035 11327 10700 14469  8518  7062
  5392  3808  7859  2036  1725  1222   694  6777   419   756   511   200
  5691   207   477   335    88  7970   117   351   241    80  5375    75
   185   176    49  6093    49   179    79    44  4957    55    74   102
    19  4265    30    60    65    18  3039    22    65    31    12  4464
    25    41    39    24 26894]
Значения кол-ва ингредиентов: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65]
Число значений кол-ва ингредиентов: 65


## Лабораторная работа №1.2

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
rows = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int64, skiprows=1)
rows[:, 1][rows[:, 1] == 0] = 1
rows_less_6_ingr = rows[rows[:, 2] <= 5]
print(type(rows[:, 2] <= 5))
print(rows_less_6_ingr)

<class 'numpy.ndarray'>
[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
rows_1 = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.float64, skiprows=1)
rows_1[:, 1][rows_1[:, 1] == 0] = 1
print(type(rows_1[:, 1] == 0))
rows_1[:, 1] = rows_1[:, 2]/rows_1[:, 1]
print(rows_1[:, 1])
print(rows_1[:, 1].max())

<class 'numpy.ndarray'>
[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
rows_sort_by_time = rows[rows[:, 1].argsort()]
print(type(rows[:, 1].argsort()))
print(rows[[89843, 1740]])
print(rows_sort_by_time)
print(rows_sort_by_time[-100:, 2].sum()/100)

<class 'numpy.ndarray'>
[[4896    1   14]
 [6975    1    8]]
[[ 4896     1    14]
 [ 6975     1     8]
 [ 3492     1     7]
 ...
 [60218    65    14]
 [78310    65    12]
 [81993    65    14]]
9.96


In [ ]:
print(rows_sort_by_time[-100:, 2].sum()/100)

9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
print(rows[np.random.choice(len(rows), size=10)])
print(len(rows))
print(rows.shape)

[[190539     65      5]
 [ 58855     62      6]
 [ 55489     65     11]
 [211366     25      7]
 [193535     10      8]
 [327952     65     11]
 [432518     20     11]
 [ 48227     30      7]
 [361828     35      6]
 [346169     65     17]]
100000
(100000, 3)


In [ ]:
type(np.random.choice(len(rows), size=10))


numpy.ndarray

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
aver_ingr_value = rows[:, 2].sum()/len(rows[:, 2])
print(100 * len(rows[rows[:, 2] < aver_ingr_value]) / len(rows))

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
easy_recipe = rows[np.where((rows[:, 1] <= 20) & (rows[:, 2] <= 5))]
hard_recipe = rows[np.where((rows[:, 1] > 20) | (rows[:, 2] > 5))]
easy, hard = np.array([[1]] * len(easy_recipe)), np.array([[0]] * len(hard_recipe))
easy_recipe, hard_recipe = np.append(easy_recipe, easy, axis=1), np.append(hard_recipe, hard, axis=1)
new_recipe_dataset = np.concatenate((easy_recipe, hard_recipe), axis=0)
print(new_recipe_dataset)

[[446597     15      5      1]
 [204134      5      3      1]
 [ 25623      6      4      1]
 ...
 [287943     85     15      0]
 [498432     65     15      0]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
print(len(easy_recipe)/len(new_recipe_dataset)*100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
short_recipe = rows[rows[:, 1] < 10]
middle_recipe = rows[np.where((rows[:, 1] > 10) & (rows[:, 1] < 20))]
long_recipe = rows[rows[:, 1] >= 20]
a = min(len(short_recipe), len(middle_recipe), len(long_recipe))
mass = np.stack((short_recipe[:a], middle_recipe[:a], long_recipe[:a]))
print(mass, mass.shape)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      1      9]
  [370915      5      4]]

 [[ 33941     18      9]
  [446597     15      5]
  [ 81006     12      7]
  ...
  [278297     12      7]
  [ 66970     15      8]
  [ 90921     18      8]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]] (3, 7588, 3)


In [ ]:
import numpy as np
a = np.arange(1, 10).reshape(3, 3)
print(a)
b = a.sum(axis = 1)
print()
print(b)
c = b ** 2
print()
print(c[:2:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 6 15 24]

[ 36 225]


In [ ]:
print(f'{100 * (rows[:,2] < rows[:,2].mean()).sum()/rows.shape[0]:2.2f}%')

58.80%
